### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by JadeXIN** [HKUST-KnowComp/ELWSMP#4]
When I run the program, I got this error:
Traceback (most recent call last):
  File "linkyelp.py", line 12, in <module>
    init_logging('log/flat-yelp-{}.log'.format(str_today), mode='a', to_stdout=True)
  File "/home/uqkxin/ELWSMP-master/utils/loggingutils.py", line 7, in init_logging
    handlers.append(logging.FileHandler(logfile, mode=mode))
  File "/home/uqkxin/anaconda3/envs/xkx_env/lib/python3.6/logging/__init__.py", line 1032, in __init__
    StreamHandler.__init__(self, self._open())
  File "/home/uqkxin/anaconda3/envs/xkx_env/lib/python3.6/logging/__init__.py", line 1061, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/home/uqkxin/ELWSMP-master/log/flat-yelp-19-07-12.log'

Where is this log file? Or is there anything I need to do before running the program?

**Comment by hldai** [comment]
You need to create a folder named "log" under the project directory.

**Comment by JadeXIN** [comment]
thank you~
